package li.doerf.hacked

enum class CustomEvent {
    FIRST_ACCOUNT_ADDED,
    ACCOUNT_ADDED,
    ACCOUNT_DELETED,
    CHECK_FOR_BREACHES,
    RELOAD_BREACHED_SITES,
    BREACH_ACKNOWLEDGED,
    RATE_NOW,
    RATE_LATER,
    RATE_NEVER,
    CHECK_PASSWORD_PWNED,
    BACKGROUND_SYNC_ENABLED,
    BACKGROUND_SYNC_DISABLED,
    DISMISS_INITIAL_HELP,
    PASSWORD_PWNED_EXCEPTION,
    PASSWORD_NOT_PWNED,
    PASSWORD_PWNED,
}