apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    compileSdk 37
    buildToolsVersion = '37.0.0'

    defaultConfig {
        applicationId "li.doerf.hacked"
        minSdk 23
        targetSdk 37
        versionCode 121
        versionName "3.9.0"
        multiDexEnabled true
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-dbg'
        }
        release {
            minifyEnabled false
        }
    }
    buildFeatures {
        compose true
        buildConfig true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    namespace 'li.doerf.hacked'
}

dependencies {
    implementation "androidx.core:core-ktx:$androidx_core_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinx_coroutines_version"

    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:$localbroadcastmanager_version"
    implementation "com.google.android.material:material:$material_version"
    implementation("androidx.work:work-runtime:$work_version")
    implementation("androidx.work:work-runtime-ktx:$work_version")
    implementation "androidx.constraintlayout:constraintlayout:$constraintlayout_version"
    implementation "com.google.android.play:review:$play_review_version"
    implementation "com.google.android.play:review-ktx:$play_review_version"
    implementation "com.google.android.gms:play-services-base:$play_services_base_version"

    // jetpack compose
    implementation platform("androidx.compose:compose-bom:$compose_bom_version")
    implementation "androidx.activity:activity-compose:$activity_compose"
    implementation "androidx.compose.material3:material3"
    implementation "androidx.compose.material:material-icons-extended"
    implementation "androidx.compose.animation:animation"
    implementation "androidx.compose.ui:ui-tooling-preview"
    implementation "androidx.navigation:navigation-compose:$nav_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-compose:$lifecycle_version"
    implementation "io.coil-kt:coil-compose:$coil_compose_version"
    implementation "androidx.compose.runtime:runtime-livedata"
    debugImplementation "androidx.compose.ui:ui-tooling"

    implementation "androidx.preference:preference-ktx:$androidx_preference_version"
    implementation "androidx.startup:startup-runtime:$startup_version"
    implementation "androidx.core:core-splashscreen:$core_splashscreen_version"

    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-rxjava2:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    annotationProcessor "androidx.room:room-compiler:$room_version"

    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-process:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    implementation(platform("com.google.firebase:firebase-bom:$firebase_bom_version"))
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    implementation "joda-time:joda-time:$jodatime_version"
    implementation 'commons-codec:commons-codec:1.17.0'
    implementation "com.google.code.gson:gson:$gson_version"
    implementation "com.squareup.picasso:picasso:$picasso_version"

    implementation "com.github.kittinunf.fuel:fuel:$fuel_version"
    implementation "com.github.kittinunf.fuel:fuel-coroutines:$fuel_version"
    implementation "com.github.kittinunf.fuel:fuel-jackson:$fuel_version"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:$jackson_version"

    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    androidTestImplementation "androidx.work:work-testing:$work_version"
}

repositories {
    mavenCentral()
}
