name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Decode google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: mkdir -p app/src/debug && echo $FIREBASE_CONFIG > app/src/debug/google-services.json
    - name: Build with Gradle
      run: ./gradlew dependencies assembleDebug
